# Generated by Django 5.2.1 on 2025-08-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapi', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
