# Generated by Django 5.1 on 2025-05-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='artwork/')),
                ('is_user_uploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='materials/')),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait'), ('square', 'Square')], max_length=10)),
                ('price_multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='frames/')),
                ('price_addition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supported_sizes', models.ManyToManyField(related_name='frames', to='artshop.size')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizedArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_image', models.ImageField(upload_to='customized_artworks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artshop.artwork')),
                ('selected_frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artshop.frame')),
                ('selected_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artshop.material')),
                ('selected_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artshop.size')),
            ],
        ),
    ]
