# Generated by Django 5.1 on 2025-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedartwork',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customizedartwork',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customizedartwork',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
