# Generated by Django 5.2.1 on 2025-05-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedartwork',
            name='original_artwork_category',
        ),
        migrations.AddField(
            model_name='customizedartwork',
            name='original_artwork_category_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artshop.artworkcategoryimage'),
        ),
    ]
