# Generated by Django 5.2.1 on 2025-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0002_remove_customizedartwork_original_artwork_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcategoryimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
