# Generated by Django 5.2.1 on 2025-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0004_artworkcategoryimage_supported_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizedartwork',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='original_artwork',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='original_artwork_category_image',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='selected_background',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='selected_frame',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='selected_material',
        ),
        migrations.RemoveField(
            model_name='customizedartwork',
            name='selected_size',
        ),
        migrations.AlterField(
            model_name='artworkcategoryimage',
            name='supported_sizes',
            field=models.ManyToManyField(blank=True, related_name='category_images', to='artshop.size'),
        ),
    ]
